jobboard/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts.views import LoginViews, UserCreationView, ProfileView, ProfileUpdateView, ResetPasswordViews, \
    PasswordResetConfirmView, StructureCreateView, StructureProfileView, StructureUpdateView

app_name = 'user'

urlpatterns = [
    path('login/', LoginViews.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', UserCreationView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='profile_update'),

    path('structure/create/', StructureCreateView.as_view(), name='structure_create'),
    path('structure/profile/', StructureProfileView.as_view(), name='structure_profile'),
    path('structure/profile/update/', StructureUpdateView.as_view(), name='structure_update'),

    path('password-reset/', ResetPasswordViews.as_view(), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

jobboard/accounts/models.py
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser

from .vocabularies import CHOICE_DPT, CHOICE_REGIONS, CHOICE_COUNTRIES, BUSINESS_LINE_CHOICES


# from .model_mixins import GetAbsoluteMixin


class Structure(models.Model):
    WORKFORCE_CHOICES = (
        (0, '0'),
        (1, _('1 à 2 salariés')),
        (3, _('3 à 5 salariés')),
        (6, _('6 à 9 salariés')),
        (10, _('10 à 19 salariés')),
        (20, _('20 à 49 salariés')),
        (50, _('50 à 99 salariés')),
        (100, _('100 à 199 salariés')),
        (200, _('200 à 499 salariés')),
        (500, _('500 à 999 salariés')),
        (1000, _('1000 à 1999 salariés')),
        (2000, _('2000 à 4999 salariés')),
        (5000, _('5000 salariés')),
        (5001, _('5000 et plus salariés')),
        (0000, _('inconnu')),

    )

    TURNOVER_CHOICES = (
        (0, '0 - 100 K€'),
        (101, '100 - 250 K€'),
        (251, '250 - 500 K€'),
        (501, '500 - 1 M€'),
        (1001, '1 M€ - 2.5 M€'),
        (2501, '2.5 M€ - 5 M€'),
        (5001, '5 M€ - 10 M€'),
        (10001, 'Supérieur à 10 M€'),
        (0000, 'Autre - précisez'),
    )

    CATEGORY_CHOICES = (
        ('enterprise', _('Entreprise')),
        ('event', _('Événement')),
        ('non_profit_organization', _('Association')),
        ('school', _('École')),
        ('public_institution', _('Collectivité locale')),
    )

    logo = models.ImageField(
        null=True,
        blank=True,
        upload_to='logos/',
        verbose_name=_('Logo'),
    )
    juridic_name = models.CharField(
        max_length=256,
        verbose_name=_('Dénomination sociale'),
    )
    commercial_name = models.CharField(
        null=True,
        blank=True,
        max_length=256,
        verbose_name=_('Libellé commercial'),
    )
    siret = models.CharField(
        max_length=15,
        unique=True,
        verbose_name=_('SIRET')
    )
    num_tva_intracom = models.CharField(
        max_length=15,
        null=True,
        blank=True,
        unique=True,
        verbose_name=_('Numéro TVA intracommunautaire'),
    )
    description = models.TextField(
        max_length=600,  # CDC : max 600 caractères
        null=True,
        blank=True,
        verbose_name=_("Description de l'activité"),
    )
    workforce = models.IntegerField(
        choices=WORKFORCE_CHOICES,
        verbose_name=_('Effectifs'),
    )
    turnover = models.DecimalField(
        choices=TURNOVER_CHOICES,
        decimal_places=2,
        max_digits=15,
        null=True,
        blank=True,
        verbose_name=_("Chiffre d'Affaires"),
    )
    category = models.CharField(
        choices=CATEGORY_CHOICES,
        max_length=25,
        db_index=True,
        verbose_name=_('Catégorie')
    )
    business_line = models.CharField(
        choices=BUSINESS_LINE_CHOICES,
        max_length=100,
        db_index=True,
        verbose_name=_("Secteur d'activité"),
    )
    creation_date = models.DateField(
        auto_now_add=True,
        verbose_name=_('Date de création'),
    )
    address = models.TextField(
        verbose_name=_('Adresse'),
    )
    zipcode = models.CharField(
        max_length=5,
        verbose_name=_('Code Postal'),
    )
    city = models.CharField(
        max_length=60,
        verbose_name=_('Ville'),
    )
    department = models.CharField(
        choices=CHOICE_DPT,
        null=True,
        blank=True,
        max_length=3,
        db_index=True,
        verbose_name=_('Département'),
    )
    region = models.CharField(
        choices=CHOICE_REGIONS,
        null=True,
        blank=True,
        max_length=6,
        db_index=True,
        verbose_name=_('Région'),
    )
    country = models.CharField(
        choices=CHOICE_COUNTRIES,
        max_length=2,
        db_index=True,
        verbose_name=_('Pays'),
    )
    phone1 = models.CharField(
        null=True,
        blank=True,
        max_length=22,
        verbose_name=_('Téléphone fixe'),
    )
    phone2 = models.CharField(
        null=True,
        blank=True,
        max_length=22,
        verbose_name=_('Mobile'),
    )
    phone3 = models.CharField(
        null=True,
        blank=True,
        max_length=22,
        verbose_name=_('Téléphone3'),
    )
    # owners = models.ForeignKey(
    #     'accounts.ThinkcodeUser',
    #     blank=True,
    #     null=True,
    #     on_delete=models.CASCADE,
    #     related_name='owned_structures',
    #     verbose_name=_('Propriétaires'),
    # )

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     for owner in self.owners.all():
    #         owner.structures.add(self)

    def __str__(self):
        return "{} - {}".format(self.juridic_name, self.siret or "")

    creation_structure_fields = (
        'logo',
         'juridic_name',
         'commercial_name',
         'address',
         'zipcode',
         'city',
         'country',
         'phone1',
         'phone2',
         'category',
         'workforce',
         'siret',
         'num_tva_intracom',
         'turnover',
         'business_line',
         'description',
    )

    class Meta:
        verbose_name = _('Structure')


class ThinkcodeUser(AbstractUser):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    email = models.EmailField(_("Adresse email"), unique=True)

    foto = models.ImageField(
        null=True,
        blank=True,
        upload_to='fotos/',
        verbose_name=_('Photo'),
    )
    GENDER_CHOICES = (
        ('F', _('Femme')),
        ('H', _('Homme')),
    )
    gender = models.CharField(
        null=True,
        blank=True,
        verbose_name=_('Civilité'),
        choices=GENDER_CHOICES,
        max_length=1,
    )
    first_name = models.CharField(
        _('first name'), max_length=30
    )
    last_name = models.CharField(
        _('last name'), max_length=150,
    )
    birthday = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Date de naissance'),
    )
    phone = models.CharField(
        null=True,
        blank=True,
        max_length=22,
        verbose_name=_('Mobile'),
    )
    address = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('Adresse'),
    )
    zipcode = models.CharField(
        null=True,
        blank=True,
        max_length=5,
        verbose_name=_('Code Postal'),
    )
    region = models.CharField(
        choices=CHOICE_REGIONS,
        null=True,
        blank=True,
        max_length=6,
        db_index=True,
        verbose_name=_('Région'),
    )
    city = models.CharField(
        null=True,
        blank=True,
        max_length=60,
        verbose_name=_('Ville'),
    )
    country = models.CharField(
        null=True,
        blank=True,
        max_length=2,
        choices=CHOICE_COUNTRIES,
        verbose_name=_('Pays'),
    )
    # is_qualified = models.BooleanField(
    #     default=False,
    #     verbose_name=_('Abonné Qualifié'),
    # )

    projects = models.TextField(_('projets'), null=True, blank=True, max_length=2000, default='none')

    # cv = models.FileField(_('cv'), null=True, blank=True, upload_to='cv/')

    url_git = models.URLField(null=True, blank=True, verbose_name=_('URL PROFIL GIT'))

    url_site = models.URLField(null=True, blank=True, verbose_name=_('URL SITE RÉALISÉ'))

    structure = models.ForeignKey(
        Structure,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='owner',
        verbose_name=_('Structure'),
    )
    is_employer = models.BooleanField(
        default=False,
        verbose_name=_('Thinkcode User Employer'),
    )

    # @property
    # def active_subscription(self):
    #     return Subscription.active_objects.filter(user=self).first()

    def save(self, *args, **kwargs):
        # self.check_is_qualified()
        super().save(*args, **kwargs)

    # qualified_fields = (
    #     'first_name',
    #     'last_name',
    # )

    creation_employeruser_fields = (
        'foto',
        'gender',
        'first_name',
        'last_name',
        'birthday',
        'phone',
        'address',
        'zipcode',
        'city',
        'country',
        'projects',
        'url_git',
        'url_site',
        'is_employer',
        'email',
        'password1',
        'password2',
    )

    creation_candidateuser_fields = (
        'foto',
        'gender',
        'first_name',
        'last_name',
        'birthday',
        'phone',
        'address',
        'zipcode',
        'city',
        'country',
        'projects',
        'url_git',
        'url_site',
        'is_employer',
        'email',
        'password1',
        'password2',
    )

    update_candidateuser_fields = (
        'foto',
        'gender',
        'first_name',
        'last_name',
        'birthday',
        'phone',
        'address',
        'zipcode',
        'city',
        'country',
        'projects',
        'url_git',
        'url_site',
        'is_employer',
        'email',
    )

    # def check_is_qualified(self):
    #     for field in self.qualified_fields:
    #         if not getattr(self, field, None):
    #             self.is_qualified = False
    #             break
    #     else:
    #         self.is_qualified = True

jobboard/accounts/views.py
import datetime
from urllib.parse import quote_plus

from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordResetView as BasePasswordResetView, \
    PasswordResetConfirmView as BasePasswordResetConfirmView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render
from django.views.generic import FormView, DetailView, UpdateView, CreateView

from .forms import ThinkcodeUserCreationForm, StructureFormClass
from .models import ThinkcodeUser, Structure


class LoginViews(SuccessMessageMixin, BaseLoginView):
    template_name = 'registration/login.html'
    success_message = _("Vous avez été connecté avec succès")

    def form_valid(self, form):
        response = super().form_valid(form)
        # if not form.get_user().is_qualified:
        #     # If the user has not complete his profile we notify him to do so.
        #     messages.add_message(
        #         self.request,
        #         messages.INFO,
        #         _("Merci de compléter entièrement votre profil pour qu'il soit considéré comme 'qualifié'"),
        #     )
        return response


class UserCreationView(SuccessMessageMixin, FormView):
    template_name = 'registration/signup.html'
    form_class = ThinkcodeUserCreationForm
    success_message = _(
        "Votre compte a été créé")

    def form_valid(self, form):
        user = form.save(commit=False)
        email = user.email
        user.username = email
        user.save()
        # subtype_display=SubscriptionType.objects.first()
        # today = datetime.date.today()
        # Subscription.objects.create(user=user, is_active=True, start_date=today, subscription_type=subtype_display)
        # confirmation_key = user.get_confirmation_key()
        # url = self.request.build_absolute_uri(reverse('user:email_confirm'))
        # url_complete = url + "?token=" + confirmation_key + "&email=" + quote_plus(email)
        # subject, from_email, to = _("[THINKCODE] Merci de confirmer votre email"), settings.THINKCODE_EMAIL_FROM, email
        #
        # text_content = '' \
        #                'Bonjour' \
        #                'Cliquez sur le lien suivant pour terminer votre inscription sur Mixity.' \
        #                'f"{url}?token={confirmation_key}&email={quote_plus(email)}"'
        #
        # html_content = render_to_string('accounts/confirm_email.html', {'url': url_complete})
        #
        # msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        # msg.attach_alternative(html_content, "text/html")
        # msg.send()
        # print(f"Allez à l'adresse {url}?token={confirmation_key}&email={quote_plus(email)}")

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


class ProfileView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'accounts/profile.html'

    def get_object(self, **kwargs):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'accounts/profile_update.html'
    model = ThinkcodeUser
    fields = ThinkcodeUser.update_candidateuser_fields
    success_message = _("Votre profil a été enregistré")

    def get_object(self, **kwargs):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.get_object()
        return context

    def get_success_url(self):
        # if not self.get_object().is_qualified:
        #     messages.warning(
        #         self.request,
        #         _("Merci de compléter entièrement votre profil pour qu'il soit considéré comme \"qualifié\""),
        #     )
        return reverse('user:profile')


class ResetPasswordViews(SuccessMessageMixin, BasePasswordResetView):
    #html_email_template_name = 'registration/password_reset_email.html'
    template_name = 'registration/password_reset.html'
    success_message = _("Mail envoyé !")
    success_url = reverse_lazy('user:password_reset_done')


class PasswordResetConfirmView(BasePasswordResetConfirmView):
    success_url = reverse_lazy('user:password_reset_complete')


class StructureCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Structure
    template_name = 'accounts/structure_create.html'
    success_message = _("Nouvelle structure validée")
    fields = Structure.creation_structure_fields

    def save(self, commit=True):
        instance = super().save(commit=commit)
        self.request.user.structure.add(instance)
        return instance

    def form_valid(self, form):
        response = super(StructureCreateView, self).form_valid(form)
        self.object.save()
        self.request.user.structure.add(self.object)
        return response

    def get_success_url(self):
        return reverse('user:structure_profile')


class StructureProfileView(LoginRequiredMixin, DetailView):
    model = Structure
    template_name = 'accounts/structure_profile.html'

    def get_object(self, **kwargs):
        return self.request.user.structure


class StructureUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Structure
    fields = Structure.creation_structure_fields
    template_name = 'accounts/structure_update.html'
    success_message = _("Vous avez mis à jour la structure")

    def get_object(self, **kwargs):
        return self.request.user.structure

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.get_object()
        return context

    def get_success_url(self):
        # if not self.get_object().is_qualified:
        #     messages.warning(
        #         self.request,
        #         _("Merci de compléter entièrement votre profil pour qu'il soit considéré comme \"qualifié\""),
        #     )
        return reverse('user:structure_profile')

jobboard/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load i18n static %}
{% load bootstrap4 %}

{% block content %}

<section class="container bg--gradient full-height">
  <div class="profile">
    <div class="profile__left">
      <div class="profile__image">
        {% if user.foto %}
          <div class="profile__image">
            <img src="{{ user.foto.url }}" alt="Photo de profil" />
          </div>
        {% else %}
          <div class="profile__image profile__image--empty">
            <i class="fas fa-user"></i>
          </div>
        {% endif %}
      </div>
      <a href="{% url 'user:profile_update' %}" class="button button--primary-dark button--sm button--circle">
        <i class="fas fa-pen"></i> modifier vos informations
      </a>
    </div>
    <div class="profile__right">
      <h1 class="profile__title">Mes informations</h1>

      <article class="card">
        <h2 class="title--h2">Mes informations personnelles</h2>
        <p>
          <strong>{% if user.gender == 'F' %}Mme{% elif user.gender == 'M' %}M.{% endif %} {{user.last_name|default:''}} {{user.first_name|default:''}}</strong><br>
          {% if user.commercial_name and user.company %} {{user.commercial_name}} à {{user.company}}{% endif%}
        </p>
        <p>
          Addresse :
          {{user.address|default:''}} {{user.zipcode|default:''}} {{user.city|default:''}} {{user.region|default:''}} {{user.country|default:''}}<br>
          Téléphone : {{user.phone|default:''}}<br>
          Email : {{user.email|default:''}}<br>
        </p>

        <p>Naissance : {{user.birthday|default:''}}</p>

      </article>
    </div>
  </div>
</section>

{% endblock %}

jobboard/accounts/templates/accounts/profile_update.html
{% extends "base.html" %}
{% load i18n static %}
{% bootstrap4 %}

{% block content %}

<section class="container bg--gradient">
  <div class="profile">
    <div class="profile__left">
      {% if object.foto %}
        <div class="profile__image">
          <img src="{{ object.foto.url }}" alt="Photo de profil" />
        </div>
        <label for="id_foto" class="button button--primary-dark button--sm button--circle">
          <i class="fas fa-pen"></i> Editer l'image
        </label>
      {% else %}
        <div class="profile__image profile__image--empty">
          <i class="fas fa-user"></i>
        </div>
        <label for="id_foto" class="button button--primary-dark button--sm button--circle">
          <i class="fas fa-pen"></i> Ajouter une image
        </label>
      {% endif %}

    </div>
    <div class="profile__right">
      <h1 class="profile__title">Modifier vos informations personnelles</h1>
      <article class="{% if user.is_organisation %}card__organisation bg--gradient-secondary-dark{% else %}card{% endif %}">

        {% include 'includes/form.html' with form=form action_url="user:profile_update" submit="Enregistrer" method="post" %}

      </article>
    </div>
  </div>
</section>

{% endblock %}

jobboard/accounts/templates/accounts/structure_create.html
{% extends "base.html" %}
{% load i18n static %}
{% load bootstrap4 %}

{% block content %}
  <section>
    <div class="col col--2 col--full full-height">
      <div class="container">
        <article>
          <h2 class="title--h2">Créer une Structure</h2>

          {% include 'includes/form.html' with form=form submit="Créer votre structure" method="post" %}
        </article>
      </div>
    </div>
  </section>

{% endblock %}

jobboard/accounts/templates/accounts/structure_profile.html
{% extends "base.html" %}
{% load i18n static %}
{% load bootstrap4 %}

{% block content %}

<section class="container bg--gradient">
  <div class="profile">
    <div class="profile__left">
      {% if object.logo %}
        <div class="profile__image">
          <img src="{{ object.logo.url }}" alt="Photo de profil" />
        </div>
        <label for="id_foto" class="button button--primary-dark button--sm button--circle">
          <i class="fas fa-pen"></i> Editer l'image
        </label>
      {% else %}
        <div class="profile__image profile__image--empty">
          <i class="fas fa-user"></i>
        </div>
        <label for="id_foto" class="button button--primary-dark button--sm button--circle">
          <i class="fas fa-pen"></i> Ajouter une image
        </label>
      {% endif %}
    </div>
      <a href="{% url 'user:structure_update' %}" class="button button--primary-dark button--sm button--circle">
        <i class="fas fa-pen"></i> modifier les informations de la Structure
      </a>
  </div>
</section>

{% endblock %}

jobboard/accounts/templates/accounts/structure_update.html
{% extends "base.html" %}
{% load i18n static %}
{% load bootstrap4 %}

{% block content %}

<section class="container bg--gradient">
  <div class="profile">
    <div class="profile__left">
      {% if object.foto %}
        <div class="profile__image">
          <img src="{{ object.foto.url }}" alt="Photo de profil" />
        </div>
        <label for="id_foto" class="button button--primary-dark button--sm button--circle">
          <i class="fas fa-pen"></i> Editer l'image
        </label>
      {% else %}
        <div class="profile__image profile__image--empty">
          <i class="fas fa-user"></i>
        </div>
        <label for="id_foto" class="button button--primary-dark button--sm button--circle">
          <i class="fas fa-pen"></i> Ajouter une image
        </label>
      {% endif %}

    </div>
    <div class="profile__right">
      <h1 class="profile__title">Modifier vos informations personnelles</h1>
      <article class="{% if user.is_organisation %}card__organisation bg--gradient-secondary-dark{% else %}card{% endif %}">

        {% include 'includes/form.html' with form=form action_url="user:structure_update" submit="Enregistrer" method="post" %}

      </article>
    </div>
  </div>
</section>

{% endblock %}